### ISSUE TITLE
Failure with missing file DMA_AL4.json

### ISSUE THREAD

**Issue by floybix** [moja-global/FLINT.Example#18]
**Describe the bug**
Running the Chapman-Richards spatial example, the run fails and reports a FileNotFoundException (see below for full output).

**To Reproduce**
* Follow instructions in `README.md` to run the Chapman-Richards spatial example.

**Expected behavior**
Something like `Started ... onOutputStep ... Finished`.

**Observed behavior**
```
C:\Users\Felix\Dev\FLINT.example\Run_Env>C:\Users\Felix\Dev\FLINT\Source\build\bin\Debug\moja.cli.exe --config config/forest_config.json --config config/libs.gdal.chaprich.win.json --config_provider config/forest_provider.json
<2020-07-12 12:11:54.533434> (info) - Config has files: 2
<2020-07-12 12:11:54.534431> (info) - Using Logging Configuration: internal default
<2020-07-12 12:11:54.534431> (info) - Using configurations:
<2020-07-12 12:11:54.536580> (info) - config/forest_config.json
<2020-07-12 12:11:54.537425> (info) - config/libs.gdal.chaprich.win.json
<2020-07-12 12:11:54.537425> (info) - Using provider configurations:
<2020-07-12 12:11:54.538420> (info) - config/forest_provider.json
<2020-07-12 12:11:54.616213> (info) - Using operation manager: Simple
<2020-07-12 12:11:54.752561> (fatal) - main(296) - C:\Users\Felix\Dev\FLINT\Source\moja.modules.gdal\src\rasterreadergdal.cpp(67): Throw in function class Poco::Dynamic::Struct<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > __cdecl moja::modules::gdal::MetaDataRasterReaderGDAL::readMetaData(void) const
Dynamic exception type: struct boost::wrapexcept<struct moja::datarepository::FileNotFoundException>
std::exception::what: Unknown exception
[struct moja::datarepository::tag_filename * __ptr64] = C:\Users\Felix\Dev\FLINT.example\Run_Env\data\DMA_AL4.json
```

**Operating Environment:**
 - Windows 10 Home v1903
- moja-global/FLINT.example@59107c2
- moja-global/FLINT@c2cb1e3
- moja-global/vcpkg@b4dcc5ceb

**Additional context**
I see there is a file `Run_Env\data\DMA_AL4.geojson` but not sure if that is the same.

**Comment by gmajan** [comment]
Thank you Felix. Since this is a problem with the Chapman-Richards module, I think @leitchy might be the best person to help but school holidays might be causing some delays.

**Comment by leitchy** [comment]
Hi Felix
,
This appears to be the same problem as with [Issue 17](https://github.com/moja-global/FLINT.Example/issues/17), you are running against a version of the FLINT that doesn't support the feature.

There were 2 options with the meta data required problem, use blank json files for each required meta data file OR make the requirement optional. For our use of the files we don't use the meta data, Chapman Richards doesn't either. GCBM does.

I selected the optional method and added the flag in FLINT to handle this. You can see in the [commit](https://github.com/moja-global/FLINT/commit/4a7cb58aa33d2f7ceac73fb952d6f0f9dbd3386e) the `metadata_required` flag has been added to the gdal raster reader provider. Chapman Richards makes use of this flag in the [provider config](https://github.com/moja-global/FLINT.Example/blob/master/Run_Env/config/forest_provider.json)

**Comment by floybix** [comment]
That makes sense. Thank you for your comprehensive explanation of the problem, I appreciate it.
