### ISSUE TITLE
Add video link in README

### ISSUE THREAD

**Issue by shloka-gupta** [moja-global/FLINT.Example#23]
**What does the current documentation state?**
-- No link present --

**Where is this stated?**
https://github.com/moja-global/FLINT.Example#readme

**Why do you want to improve the statement?**
So that the first-time users/developers can navigate to the video with ease.

**Proposed statement**
Add the video link.

**Additional info**
--

**Comment by shloka-gupta** [comment]
@shubhamkarande13 can I work on this?

**Comment by shubhamkarande13** [comment]
Go ahead!
