### ISSUE TITLE
OpenSSL REQUIRED error

### ISSUE THREAD

**Issue by leitchy** [moja-global/FLINT.Example#7]
**What does the current documentation state?**
# Create a build folder under the Source folder

```
mkdir -p Source\build
cd Source\build

cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=C:\Development\Software\moja -DVCPKG_TARGET_TRIPLET=x64-windows -DENABLE_TESTS=OFF -DCMAKE_TOOLCHAIN_FILE=c:\Development\moja-global\vcpkg\scripts\buildsystems\vcpkg.cmake ..

```

**Where is this stated?**
This is in the master branch README.md

**Why do you want to improve the statement?**
Some errors when building on Windows - "OpenSSL REQUIRED"

**Proposed statement**
Add

```
-DOPENSSL_ROOT_DIR=c:\Development\moja-global\vcpkg\installed\x64-windows
```

**Additional info**

**Comment by sjbcastro** [comment]
Hi Jim,

I've not been assigned anything yet, so I've just gone poking around in the moja repos to get familiarised etc. I also encountered this error when building and adding the above did solve the openSSL error. However once I got past the openSSL error I got another error instead: 

```
CMake Error at C:/Development/moja-global/vcpkg/scripts/buildsystems/vcpkg.cmake:288 (_find_package):
  Could not find a package configuration file provided by "fmt" with any of
  the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  moja.modules.chapman_richards/CMakeLists.txt:9 (find_package)
```

I couldn't find either fmtConfig.cmake or fmt-config.cmake in C:\Development\ so it's possible that I've messed something up earlier when building the FLINT sources. Any ideas?

I'd be happy to put in a pull request for this issue but I figured it'd make sense to get the FLINT example built first, just in case there is another argument cmake needs. Let me know what you think.

Cheers!

**Comment by sulays** [comment]
Hi, I think the error is coming because fmt package is not installed in the vcpkg. 
Running `vcpkg.exe install fmt:x64-windows`  in the vcpkg directory will get rid of the error.

**Comment by sjbcastro** [comment]
Thanks @sulays, that fixed it :)

**Comment by sjbcastro** [comment]
Put in a pull request here: https://github.com/moja-global/FLINT.example/pull/11

**Comment by leitchy** [comment]
thanks @sjbcastro and @sulays!
