### ISSUE TITLE
@all-contributors add

### ISSUE THREAD

**Issue by leitchy** [moja-global/FLINT.Example#8]
@all-contributors please add @malfrancis for code

**Comment by leitchy** [comment]
@all-contributors add @malfrancis for code

**Comment by leitchy** [comment]
@all-contributors add @ sjbcastro for documentation

**Comment by leitchy** [comment]
@all-contributors add @sjbcastro for documentation

**Comment by leitchy** [comment]
@all-contributors add @parth-gr for documentation

**Comment by gmajan** [comment]
Thank you Jim. I liked only Parth but thank you for putting all coders in.
